### ISSUE TITLE
hey there, this is for the vape lite cheat (in dangerous section)

### ISSUE THREAD

**Issue by 15ggd** [MCHCCRG/MCHCCRG.github.io#1]
Identifies VirtualBox via ACPI registry values (likely an anti-VM Malware)

Checks BIOS information in registry (BIOS information is often read in order to detect sandboxing environments.) 

Executes dropped EXE 
Themida packer(Detects Themida, an advanced Windows software protection system.)

Checks whether UAC is enabled 

Suspicious use of NtSetInformationThreadHideFromDebugger 

Enumerates system info in registry

Modifies registry class 

Suspicious behavior: EnumeratesProcesses 

Suspicious behavior: GetForegroundWindowSpam 

Suspicious behavior: NtCreateUserProcessBlockNonMicrosoftBinary 

Suspicious use of AdjustPrivilegeToken 

Suspicious use of FindShellTrayWindow 

Suspicious use of SendNotifyMessage

Suspicious use of SetWindowsHookEx 

Suspicious use of WriteProcessMemory 

![image](https://github.com/MCHCCRG/MCHCCRG.github.io/assets/161390470/259dd533-7f77-478d-b1d7-db6f2d8af024)

**Comment by 15ggd** [comment]
it is a malware, you might as well remove it so people don't take chances

**Comment by MCHCCRG** [comment]
it is in the dangerous category for a reason, and while it is suspicious, i do believe it to be safe, i checked other archives and they have the exact same vape as here, i'm going to contact them too and then decide on the future actions to be taken. I did already check this before uploading it and i do believe it to be safe.

**Comment by 15ggd** [comment]
alright

**Comment by MCHCCRG** [comment]
Doubts about the safety of the Vape Lite have been clarified, you can find our findings here https://mchccrg.github.io/announcements.html but in short, the client is safe

**Comment by TheRealNouxd** [comment]
false claims, by kangaroo (aka checked 50 times by 50 people) it has been proven to be safe a LONG time ago

**Comment by 15ggd** [comment]
> Doubts about the safety of the Vape Lite have been clarified, you can find our findings here https://mchccrg.github.io/announcements.html but in short, the client is safe. For further info contact me on discord.

alright thank you

**Comment by 15ggd** [comment]
> false claims, by kangaroo (aka checked 50 times by 50 people) it has been proven to be safe a LONG time ago

i'm just going off tria.ge, i'm not a virus expert lol just so much flags came up i deleted it and notified the owner
